eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
#配置Swagger相关信息
  instance:
      prefer-ip-address: true
      instanceId: ${server.host}:${server.port}
      status-page-url: http://${server.host}:${server.port}/swagger-ui.html
# ${server.port}为该服务的端口号
server:
  port: 8762
  host: 127.0.0.1
spring:
  application:
    name: service-flyersTMS
  datasource:
      name: test
#      url: jdbc:mysql://10.135.136.17:3306/messageboard
#      username: root
#      password: liujinlei
      url: jdbc:mysql://148.***.***:3306/message
      username: root
      password: liujinlei
      driver-class-name: com.mysql.jdbc.Driver
#      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:sqlmap/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.flyerstms.flyerstms.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

